version: '3.7'

services:

  php:
    build: ./
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'jjj'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'jjj123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'jjj123'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - donnees-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1        
    depends_on:
      - db

# Names our volume
volumes:
  donnees-db: